import React, { createContext, useContext, useState } from "react";

const T = {
  ru: {
    nav_home: "Домой",
    nav_sections: "Секции",
    nav_schedule: "Расписание",
    nav_chat: "Чат",
    nav_profile: "Профиль",
    login_title: "Вход в систему",
    login_btn: "Войти",
    login_loading: "Вход...",
    no_account: "Нет аккаунта?",
    reg_title: "Регистрация",
    reg_subtitle: "Только для студентов",
    reg_step1: "Шаг 1 из 2 — данные аккаунта",
    reg_step2: "Шаг 2 из 2 — подтверждение",
    reg_send_code: "Получить SMS-код →",
    reg_sending: "Отправка...",
    reg_confirm: "Подтвердить и зарегистрироваться",
    reg_checking: "Проверка...",
    reg_back_login: "← Уже есть аккаунт",
    reg_back_data: "← Изменить данные",
    reg_agree: "Я согласен(а) с",
    reg_law: "Федеральным законом №152-ФЗ «О персональных данных»",
    reg_sms_sent: "SMS-код отправлен на номер",
    reg_demo: "демо-режим: код",
    reg_enter_code: "Введите 4-значный код",
    reg_success: "Регистрация успешна! Теперь войдите.",
    field_name: "ФИО",
    field_login: "Логин",
    field_password: "Пароль (мин. 6 символов)",
    field_group: "Группа (например гК-31)",
    field_phone: "+996 700 000 000",
    field_old_pass: "Старый пароль",
    field_new_pass: "Новый пароль",
    field_message: "Введите сообщение...",
    search_placeholder: "🔍 Поиск секции",
    sections_empty: "Секции ещё не созданы",
    sections_not_found: "Ничего не найдено",
    schedule_title: "Расписание",
    schedule_count: "занятий на неделе",
    schedule_empty: "Расписание пока пустое",
    schedule_edit: "Изменить",
    schedule_time: "время",
    schedule_lessons: "зан.",
    all_sections: "Все секции",
    sections_available: "секций доступно",
    sections_none: "Секций пока нет",
    loading: "Загрузка...",
    logout: "Выйти",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    send: "Отправить",
    attend_title: "Посещаемость",
    attend_mark: "Отметить посещаемость",
    attend_present: "Присутствовал",
    attend_absent: "Отсутствовал",
    attend_save: "Сохранить отметки",
    notif_approved: "Заявка одобрена",
    notif_cancelled: "Заявка отклонена",
    notif_pending: "Новая заявка",
    err_login_empty: "Введите логин и пароль",
    err_login_fail: "Ошибка входа",
    err_server: "Сервер не отвечает",
    err_no_name: "Введите ФИО",
    err_no_login: "Введите логин",
    err_login_short: "Логин — минимум 3 символа",
    err_no_pass: "Введите пароль",
    err_pass_short: "Пароль — минимум 6 символов",
    err_no_phone: "Введите номер телефона",
    err_bad_phone: "Некорректный номер телефона",
    err_no_agree: "Необходимо согласиться с обработкой персональных данных",
    err_code_empty: "Введите код из SMS",
    err_code_wrong: "Неверный код. Попробуйте ещё раз",
    err_send_code: "Ошибка отправки кода",
    err_reg: "Ошибка регистрации",
    err_sections_load: "Не удалось загрузить секции. Проверьте соединение.",
    err_no_file: "Выберите файл",
    err_photo_upload: "Ошибка при загрузке фото",
    err_file_none: "Файл не выбран",
    err_pass_fields: "Введите старый и новый пароли",
    err_pass_change: "Ошибка смены пароля",
    err_server_short: "Ошибка сервера",
    err_cancel_booking: "Отменить заявку?",
    err_booking_only_students: "Запись доступна только студентам!",
    err_booking_fail: "Ошибка при записи!",
    err_server_unavail: "Сервер недоступен",
    err_section_not_found: "Секция не найдена",
    err_section_deleted: "Возможно, она была удалена или ещё не существует",
    role_coach: "👨‍🏫 Преподаватель",
    role_student: "✓ Студент",
    role_no_coach: "Без тренера",
    profile_coach: "Профиль преподавателя",
    profile_student: "Профиль студента",
    profile_not_auth: "Не авторизован",
    profile_update_photo: "Обновить фото",
    profile_photo_updated: "Фото обновлено!",
    profile_healthdoc: "Мед. справка",
    profile_upload_doc: "Загрузить справку",
    profile_doc_uploaded: "Справка загружена",
    profile_my_sections: "Мои секции",
    profile_no_sections: "Нет принятых секций",
    profile_my_bookings: "Мои заявки",
    profile_no_bookings: "Нет ожидающих заявок",
    profile_cancel_booking: "Отменить заявку",
    profile_booking_status: "Статус:",
    profile_change_pass: "Сменить пароль ▾",
    profile_update_pass: "Обновить пароль",
    profile_pass_updated: "Пароль обновлён",
    chat_students: "Студенты",
    chat_coaches: "Преподаватели",
    chat_contacts: "контактов",
    chat_no_contacts: "Нет доступных контактов",
    chat_start: "Начните переписку",
    chat_student_label: "Студент",
    chat_coach_label: "Преподаватель",
    chat_you: "Вы",
    section_title: "Секция",
    section_coach: "Тренер:",
    section_description: "Описание:",
    section_no_desc: "Описание отсутствует",
    section_spots: "Занято:",
    section_book: "Отправить заявку »",
    section_booked: "✅ Заявка отправлена тренеру!",
    go_back: "← Назад",
    sign_in: "Войти",
    tp_my_sections: "Мои секции",
    tp_add: "Добавить",
    tp_new_section: "Новая секция",
    tp_section_name: "Название секции *",
    tp_section_place: "Место проведения *",
    tp_section_desc: "Описание",
    tp_color: "Цвет",
    tp_max_students: "Макс. студентов",
    tp_section_photo: "Фото секции",
    tp_create_section: "Создать секцию",
    tp_save: "Сохранить",
    tp_show_students: "Посмотреть студентов",
    tp_hide_students: "Скрыть студентов",
    tp_students: "Студенты",
    tp_health_doc: "мед. справка",
    tp_no_doc: "нет справки",
    tp_no_students_yet: "Пока нет студентов.",
    tp_no_sections: "Нет созданных секций",
    tp_student_requests: "Заявки студентов",
    tp_approve: "Принять",
    tp_reject: "Отклонить",
    tp_fill_required: "Заполните название и место",
    tp_section_create_err: "Ошибка при создании секции",
    tp_delete_section_confirm: "Удалить секцию?",
    tp_section_color: "Цвет секции",
    profile_change_name: "Изменить имя",
    profile_new_name_placeholder: "Новое имя",
    profile_save_name: "Сохранить имя",
    profile_enter_name: "Введите новое имя",
    profile_name_updated: "Имя обновлено",
    adm_panel: "Панель администратора",
    adm_tab_stats: "Статистика",
    adm_tab_users: "Пользователи",
    adm_tab_sections: "Секции",
    adm_tab_bookings: "Бронирования",
    adm_tab_logs: "Логи",
    adm_total_users: "Всего пользователей",
    adm_students: "Студенты",
    adm_coaches: "Тренеры",
    adm_sections: "Секции",
    adm_bookings: "Бронирования",
    adm_messages: "Сообщений",
    adm_booking_statuses: "📊 Статусы бронирований",
    adm_pending: "Ожидают",
    adm_approved: "Принято",
    adm_cancelled: "Отменено",
    adm_schedule: "📅 Расписание",
    adm_schedule_entries: "Записей в расписании:",
    adm_search: "🔍 Поиск по имени или логину...",
    adm_people: "чел.",
    adm_col_id: "ID",
    adm_col_name: "ФИО",
    adm_col_login: "Логин",
    adm_col_role: "Роль",
    adm_col_group: "Группа",
    adm_col_student: "Студент",
    adm_col_section: "Секция",
    adm_col_date: "Дата",
    adm_col_status: "Статус",
    adm_role_admin: "Админ",
    adm_role_coach: "Тренер",
    adm_role_student: "Студент",
    adm_status_pending: "Ожидание",
    adm_status_approved: "Принят",
    adm_status_cancelled: "Отменён",
    adm_security_log: "ЖУРНАЛ БЕЗОПАСНОСТИ",
    adm_refresh: "↺ Обновить",
    adm_no_logs: "Нет записей",
    adm_delete_user: "Удалить пользователя?",
    adm_delete_section: "Удалить секцию?",
    adm_delete_booking: "Удалить запись?",
    se_title: "Моё расписание",
    se_add_lesson: "Добавить занятие",
    se_pick_day: "Выберите день недели",
    se_pick_section: "Выберите секцию",
    se_add_btn: "Добавить",
    se_save_btn: "Сохранить",
    se_empty: "Нет занятий",
    se_fill_all: "Заполните все поля",
    se_coach_only: "Доступ только для преподавателей",
    se_delete_confirm: "Удалить запись из расписания?",
    se_day_mon: "Понедельник",
    se_day_tue: "Вторник",
    se_day_wed: "Среда",
    se_day_thu: "Четверг",
    se_day_fri: "Пятница",
    att_title: "Посещаемость",
    att_all_students: "Все студенты",
    att_total: "Всего",
    att_present: "Присутствовал",
    att_absent: "Пропустил",
    att_attendance_pct: "Посещаемость:",
    att_no_records: "Записей о посещаемости нет",
    att_present_badge: "Присутствовал",
    att_absent_badge: "Пропустил",
    bc_title: "Подтвердить запись",
    bc_doc_upload: "Загрузка документов",
    bc_auto: "Автоматически",
    bc_manual: "Вручную",
    bc_coach: "Тренер:",
    bc_student: "Студент:",
    bc_date: "Дата подачи:",
    bc_confirm: "Подтвердить запись »",
    bc_no_coach: "Не назначен",
    bc_not_auth: "Необходимо войти в аккаунт",
    sl_title: "🏟️ Все секции",
    sl_no_place: "Место не указано",
    sl_no_coach: "Тренер не назначен",
    success_title: "Заявка подана",
    success_btn: "Другие секции",
    tb_no_requests: "Нет заявок",
  },
  en: {
    nav_home: "Home",
    nav_sections: "Sections",
    nav_schedule: "Schedule",
    nav_chat: "Chat",
    nav_profile: "Profile",
    login_title: "Sign In",
    login_btn: "Sign In",
    login_loading: "Signing in...",
    no_account: "No account?",
    reg_title: "Register",
    reg_subtitle: "Students only",
    reg_step1: "Step 1 of 2 — account details",
    reg_step2: "Step 2 of 2 — verification",
    reg_send_code: "Get SMS Code →",
    reg_sending: "Sending...",
    reg_confirm: "Confirm & Register",
    reg_checking: "Verifying...",
    reg_back_login: "← Already have an account",
    reg_back_data: "← Edit details",
    reg_agree: "I agree with",
    reg_law: "Federal Law No. 152-FZ «On Personal Data»",
    reg_sms_sent: "SMS code sent to",
    reg_demo: "demo mode: code",
    reg_enter_code: "Enter 4-digit code",
    reg_success: "Registration successful! Please sign in.",
    field_name: "Full name",
    field_login: "Username",
    field_password: "Password (min. 6 chars)",
    field_group: "Group (e.g. gK-31)",
    field_phone: "+996 700 000 000",
    field_old_pass: "Old password",
    field_new_pass: "New password",
    field_message: "Type a message...",
    search_placeholder: "🔍 Search sections",
    sections_empty: "No sections yet",
    sections_not_found: "Nothing found",
    schedule_title: "Schedule",
    schedule_count: "sessions this week",
    schedule_empty: "Schedule is empty",
    schedule_edit: "Edit",
    schedule_time: "time",
    schedule_lessons: "ses.",
    all_sections: "All Sections",
    sections_available: "sections available",
    sections_none: "No sections yet",
    loading: "Loading...",
    logout: "Sign Out",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    send: "Send",
    attend_title: "Attendance",
    attend_mark: "Mark Attendance",
    attend_present: "Present",
    attend_absent: "Absent",
    attend_save: "Save Attendance",
    notif_approved: "Application approved",
    notif_cancelled: "Application rejected",
    notif_pending: "New application",
    err_login_empty: "Enter username and password",
    err_login_fail: "Login failed",
    err_server: "Server is not responding",
    err_no_name: "Enter your full name",
    err_no_login: "Enter a username",
    err_login_short: "Username — at least 3 characters",
    err_no_pass: "Enter a password",
    err_pass_short: "Password — at least 6 characters",
    err_no_phone: "Enter a phone number",
    err_bad_phone: "Invalid phone number",
    err_no_agree: "You must agree to the data processing policy",
    err_code_empty: "Enter the SMS code",
    err_code_wrong: "Incorrect code. Please try again",
    err_send_code: "Failed to send code",
    err_reg: "Registration error",
    err_sections_load: "Failed to load sections. Check your connection.",
    err_no_file: "Please select a file",
    err_photo_upload: "Error uploading photo",
    err_file_none: "No file selected",
    err_pass_fields: "Enter old and new passwords",
    err_pass_change: "Password change error",
    err_server_short: "Server error",
    err_cancel_booking: "Cancel this booking?",
    err_booking_only_students: "Booking is available to students only!",
    err_booking_fail: "Booking error!",
    err_server_unavail: "Server unavailable",
    err_section_not_found: "Section not found",
    err_section_deleted: "It may have been deleted or doesn't exist yet",
    role_coach: "👨‍🏫 Coach",
    role_student: "✓ Student",
    role_no_coach: "No coach",
    profile_coach: "Coach Profile",
    profile_student: "Student Profile",
    profile_not_auth: "Not signed in",
    profile_update_photo: "Update Photo",
    profile_photo_updated: "Photo updated!",
    profile_healthdoc: "Health Document",
    profile_upload_doc: "Upload Document",
    profile_doc_uploaded: "Document uploaded",
    profile_my_sections: "My Sections",
    profile_no_sections: "No approved sections",
    profile_my_bookings: "My Applications",
    profile_no_bookings: "No pending applications",
    profile_cancel_booking: "Cancel Application",
    profile_booking_status: "Status:",
    profile_change_pass: "Change Password ▾",
    profile_update_pass: "Update Password",
    profile_pass_updated: "Password updated",
    chat_students: "Students",
    chat_coaches: "Coaches",
    chat_contacts: "contacts",
    chat_no_contacts: "No contacts available",
    chat_start: "Start a conversation",
    chat_student_label: "Student",
    chat_you: "You",
    chat_coach_label: "Coach",
    section_title: "Section",
    section_coach: "Coach:",
    section_description: "Description:",
    section_no_desc: "No description",
    section_spots: "Spots taken:",
    section_book: "Submit Application »",
    section_booked: "✅ Application sent to coach!",
    go_back: "← Back",
    sign_in: "Sign In",
    tp_my_sections: "My Sections",
    tp_add: "Add",
    tp_new_section: "New Section",
    tp_section_name: "Section name *",
    tp_section_place: "Location *",
    tp_section_desc: "Description",
    tp_color: "Color",
    tp_max_students: "Max students",
    tp_section_photo: "Section photo",
    tp_create_section: "Create Section",
    tp_save: "Save",
    tp_show_students: "View Students",
    tp_hide_students: "Hide Students",
    tp_students: "Students",
    tp_health_doc: "health doc",
    tp_no_doc: "no document",
    tp_no_students_yet: "No students yet.",
    tp_no_sections: "No sections created",
    tp_student_requests: "Student Applications",
    tp_approve: "Approve",
    tp_reject: "Reject",
    tp_fill_required: "Fill in name and location",
    tp_section_create_err: "Error creating section",
    tp_delete_section_confirm: "Delete this section?",
    tp_section_color: "Section Color",
    profile_change_name: "Change Name",
    profile_new_name_placeholder: "New name",
    profile_save_name: "Save Name",
    profile_enter_name: "Enter new name",
    profile_name_updated: "Name updated",
    adm_panel: "Admin Panel",
    adm_tab_stats: "Statistics",
    adm_tab_users: "Users",
    adm_tab_sections: "Sections",
    adm_tab_bookings: "Bookings",
    adm_tab_logs: "Logs",
    adm_total_users: "Total Users",
    adm_students: "Students",
    adm_coaches: "Coaches",
    adm_sections: "Sections",
    adm_bookings: "Bookings",
    adm_messages: "Messages",
    adm_booking_statuses: "📊 Booking Statuses",
    adm_pending: "Pending",
    adm_approved: "Approved",
    adm_cancelled: "Cancelled",
    adm_schedule: "📅 Schedule",
    adm_schedule_entries: "Schedule entries:",
    adm_search: "🔍 Search by name or username...",
    adm_people: "users",
    adm_col_id: "ID",
    adm_col_name: "Full Name",
    adm_col_login: "Username",
    adm_col_role: "Role",
    adm_col_group: "Group",
    adm_col_student: "Student",
    adm_col_section: "Section",
    adm_col_date: "Date",
    adm_col_status: "Status",
    adm_role_admin: "Admin",
    adm_role_coach: "Coach",
    adm_role_student: "Student",
    adm_status_pending: "Pending",
    adm_status_approved: "Approved",
    adm_status_cancelled: "Cancelled",
    adm_security_log: "SECURITY LOG",
    adm_refresh: "↺ Refresh",
    adm_no_logs: "No entries",
    adm_delete_user: "Delete this user?",
    adm_delete_section: "Delete this section?",
    adm_delete_booking: "Delete this booking?",
    se_title: "My Schedule",
    se_add_lesson: "Add Session",
    se_pick_day: "Select day of week",
    se_pick_section: "Select section",
    se_add_btn: "Add",
    se_save_btn: "Save",
    se_empty: "No sessions",
    se_fill_all: "Fill in all fields",
    se_coach_only: "Access for coaches only",
    se_delete_confirm: "Remove this session from schedule?",
    se_day_mon: "Monday",
    se_day_tue: "Tuesday",
    se_day_wed: "Wednesday",
    se_day_thu: "Thursday",
    se_day_fri: "Friday",
    att_title: "Attendance",
    att_all_students: "All Students",
    att_total: "Total",
    att_present: "Present",
    att_absent: "Absent",
    att_attendance_pct: "Attendance:",
    att_no_records: "No attendance records",
    att_present_badge: "Present",
    att_absent_badge: "Absent",
    bc_title: "Confirm Booking",
    bc_doc_upload: "Document Upload",
    bc_auto: "Automatic",
    bc_manual: "Manual",
    bc_coach: "Coach:",
    bc_student: "Student:",
    bc_date: "Submission date:",
    bc_confirm: "Confirm Booking »",
    bc_no_coach: "Not assigned",
    bc_not_auth: "You must be signed in",
    sl_title: "🏟️ All Sections",
    sl_no_place: "Location not specified",
    sl_no_coach: "No coach assigned",
    success_title: "Application submitted",
    success_btn: "Browse Sections",
    tb_no_requests: "No applications",
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "ru");

  const toggleLang = () => {
    const next = lang === "ru" ? "en" : "ru";
    setLang(next);
    localStorage.setItem("lang", next);
  };

  const t = (key) => T[lang]?.[key] ?? T.ru[key] ?? key;

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
