import React, { createContext, useContext } from "react";

const T = {
  ru: {
    nav_home: "Домой",
    nav_sections: "Секции",
    nav_schedule: "Расписание",
    nav_chat: "Чат",
    nav_profile: "Профиль",
    login_title: "Вход в систему",
    login_btn: "Войти",
    login_loading: "Вход...",
    no_account: "Нет аккаунта?",
    reg_title: "Регистрация",
    reg_subtitle: "Только для студентов",
    reg_step1: "Шаг 1 из 2 — данные аккаунта",
    reg_step2: "Шаг 2 из 2 — подтверждение почты",
    reg_send_code: "Получить код на почту →",
    reg_sending: "Отправка...",
    reg_confirm: "Подтвердить и зарегистрироваться",
    reg_checking: "Проверка...",
    reg_back_login: "← Уже есть аккаунт",
    reg_back_data: "← Изменить данные",
    reg_agree: "Я даю согласие на",
    reg_law: "обработку моих персональных данных",
    reg_email_sent: "Код подтверждения отправлен на адрес",
    reg_demo: "демо-режим: код",
    reg_enter_code: "Введите 4-значный код из письма",
    reg_success: "Регистрация успешна! Теперь войдите.",
    field_name: "ФИО",
    field_login: "Логин",
    field_password: "Пароль (мин. 6 символов)",
    field_group: "Группа (например гК-31)",
    field_email: "Электронная почта",
    field_old_pass: "Старый пароль",
    field_new_pass: "Новый пароль",
    field_message: "Введите сообщение...",
    search_placeholder: "🔍 Поиск секции",
    sections_empty: "Секции ещё не созданы",
    sections_not_found: "Ничего не найдено",
    schedule_title: "Расписание",
    schedule_count: "занятий на неделе",
    schedule_empty: "Расписание пока пустое",
    schedule_edit: "Изменить",
    schedule_time: "время",
    schedule_lessons: "зан.",
    all_sections: "Все секции",
    sections_available: "секций доступно",
    sections_none: "Секций пока нет",
    loading: "Загрузка...",
    logout: "Выйти",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    send: "Отправить",
    attend_title: "Посещаемость",
    attend_mark: "Отметить посещаемость",
    attend_present: "Присутствовал",
    attend_absent: "Отсутствовал",
    attend_save: "Сохранить отметки",
    notif_approved: "Заявка одобрена",
    notif_cancelled: "Заявка отклонена",
    notif_pending: "Новая заявка",
    err_login_empty: "Введите логин и пароль",
    err_login_fail: "Ошибка входа",
    err_server: "Сервер не отвечает",
    err_no_name: "Введите ФИО",
    err_no_login: "Введите логин",
    err_login_short: "Логин — минимум 3 символа",
    err_no_pass: "Введите пароль",
    err_pass_short: "Пароль — минимум 6 символов",
    err_no_email: "Введите адрес электронной почты",
    err_bad_email: "Некорректный адрес электронной почты",
    err_no_agree: "Необходимо дать согласие на обработку персональных данных",
    err_code_empty: "Введите код из письма",
    err_code_wrong: "Неверный код. Попробуйте ещё раз",
    err_send_code: "Ошибка отправки кода",
    err_reg: "Ошибка регистрации",
    err_sections_load: "Не удалось загрузить секции. Проверьте соединение.",
    err_no_file: "Выберите файл",
    err_photo_upload: "Ошибка при загрузке фото",
    err_file_none: "Файл не выбран",
    err_pass_fields: "Введите старый и новый пароли",
    err_pass_change: "Ошибка смены пароля",
    err_server_short: "Ошибка сервера",
    err_cancel_booking: "Отменить заявку?",
    err_booking_only_students: "Запись доступна только студентам!",
    err_booking_fail: "Ошибка при записи!",
    err_server_unavail: "Сервер недоступен",
    err_section_not_found: "Секция не найдена",
    err_section_deleted: "Возможно, она была удалена или ещё не существует",
    role_coach: "👨‍🏫 Преподаватель",
    role_student: "✓ Студент",
    role_no_coach: "Без тренера",
    profile_coach: "Профиль преподавателя",
    profile_student: "Профиль студента",
    profile_not_auth: "Не авторизован",
    profile_update_photo: "Обновить фото",
    profile_photo_updated: "Фото обновлено!",
    profile_healthdoc: "Мед. справка",
    profile_upload_doc: "Загрузить справку",
    profile_doc_uploaded: "Справка загружена",
    profile_my_sections: "Мои секции",
    profile_no_sections: "Нет принятых секций",
    profile_my_bookings: "Мои заявки",
    profile_no_bookings: "Нет ожидающих заявок",
    profile_cancel_booking: "Отменить заявку",
    profile_booking_status: "Статус:",
    profile_change_pass: "Сменить пароль ▾",
    profile_update_pass: "Обновить пароль",
    profile_pass_updated: "Пароль обновлён",
    profile_doc_format: "Принимаются только PNG и PDF · до 5 МБ",
    profile_doc_current: "Справка загружена",
    profile_doc_none: "Справка не загружена",
    profile_doc_replace: "Заменить справку",
    profile_photo_section: "Фотография профиля",
    profile_info_section: "Данные аккаунта",
    profile_group_label: "Группа",
    chat_students: "Студенты",
    chat_coaches: "Преподаватели",
    chat_contacts: "контактов",
    chat_no_contacts: "Нет доступных контактов",
    chat_start: "Начните переписку",
    chat_student_label: "Студент",
    chat_coach_label: "Преподаватель",
    chat_you: "Вы",
    section_title: "Секция",
    home_tab_all: "Все секции",
    home_tab_insider: "Для своих",
    home_insider_empty_student: "Вы пока не зачислены ни в одну секцию",
    home_insider_empty_coach: "У вас пока нет секций",
    home_insider_hint_student: "Здесь будут секции, в которых вы состоите",
    home_insider_hint_coach: "Здесь ваши секции — нажмите, чтобы открыть ленту объявлений",
    section_tab_info: "О секции",
    section_tab_insider: "Для своих",
    section_coach: "Тренер:",
    section_description: "Описание:",
    section_no_desc: "Описание отсутствует",
    section_spots: "Занято:",
    section_book: "Отправить заявку »",
    section_booked: "✅ Заявка отправлена тренеру!",
    section_post_placeholder: "Новость или объявление для участников...",
    section_post_publish: "Опубликовать",
    section_no_posts: "Объявлений пока нет",
    section_insider_hint: "Здесь публикуются новости и объявления только для участников секции.",
    section_no_access: "Этот раздел доступен только принятым участникам секции.",
    go_back: "← Назад",
    reg_student_id: "Номер студенческого билета",
    reg_checking_id: "Проверяем...",
    reg_id_found: "Студент найден в реестре",
    reg_id_not_found: "Студент не найден в реестре",
    reg_id_already: "Этот студбилет уже зарегистрирован",
    reg_id_hint: "Введите номер студенческого билета для проверки по реестру",
    reg_fio_section: "Введите ФИО точно как в зачётной книжке",
    reg_last_name: "Фамилия",
    reg_first_name: "Имя",
    reg_middle_name: "Отчество",
    reg_fio_mismatch: "ФИО не совпадает с данными реестра. Проверьте написание",
    reg_fullname_auto: "ФИО найдено в реестре — введите ниже для подтверждения",
    reg_group_auto: "Группа",
    adm_tab_pending: "Заявки на регистрацию",
    adm_pending_empty: "Нет заявок на регистрацию",
    adm_pending_approve: "Одобрить",
    adm_pending_reject_btn: "Отклонить",
    adm_pending_reject_title: "Причина отклонения",
    adm_pending_reject_reason: "Введите причину отклонения (необязательно)...",
    adm_pending_reject_default: "Заявка отклонена администратором",
    adm_pending_status_pending: "Ожидает",
    adm_pending_status_approved: "Одобрено",
    adm_pending_status_rejected: "Отклонено",
    reg_pending_title: "Заявка отправлена!",
    reg_pending_desc: "Ваша заявка на регистрацию принята и ожидает проверки администратором. После одобрения вы сможете войти в систему.",
    reg_optional: "необязательно",
    reg_ip_notice: "Максимум 3 заявки с одного IP за 24 часа",
    adm_registry: "Реестр",
    adm_reg_upload_title: "Загрузить список студентов",
    adm_reg_upload_hint: "CSV-файл, столбцы: номер студбилета, имя, фамилия, отчество, группа",
    adm_reg_upload_btn: "Загрузить CSV",
    adm_reg_upload_ok: "Загружено записей",
    adm_reg_upload_err: "Ошибка загрузки",
    adm_reg_count: "Студентов в реестре",
    adm_reg_col_id: "Студбилет",
    adm_reg_col_name: "ФИО",
    adm_reg_col_group: "Группа",
    adm_reg_col_login: "Аккаунт",
    adm_reg_empty: "Реестр пуст — загрузите CSV",
    adm_reg_registered: "Зарегистрирован",
    adm_reg_not_registered: "Не зарег.",
    sign_in: "Войти",
    tp_my_sections: "Мои секции",
    tp_add: "Добавить",
    tp_new_section: "Новая секция",
    tp_section_name: "Название секции *",
    tp_section_place: "Место проведения *",
    tp_section_desc: "Описание",
    tp_color: "Цвет",
    tp_max_students: "Макс. студентов",
    tp_section_photo: "Фото секции",
    tp_create_section: "Создать секцию",
    tp_save: "Сохранить",
    tp_show_students: "Посмотреть студентов",
    tp_hide_students: "Скрыть студентов",
    tp_students: "Студенты",
    tp_health_doc: "мед. справка",
    tp_no_doc: "нет справки",
    tp_no_students_yet: "Пока нет студентов.",
    tp_write_message: "Написать сообщение",
    tp_view_profile: "Профиль",
    tp_no_sections: "Нет созданных секций",
    tp_student_requests: "Заявки студентов",
    tp_approve: "Принять",
    tp_reject: "Отклонить",
    tp_fill_required: "Заполните название и место",
    tp_section_create_err: "Ошибка при создании секции",
    tp_delete_section_confirm: "Удалить секцию?",
    tp_section_color: "Цвет секции",
    profile_change_name: "Изменить имя",
    profile_new_name_placeholder: "Новое имя",
    profile_save_name: "Сохранить имя",
    profile_enter_name: "Введите новое имя",
    profile_name_updated: "Имя обновлено",
    adm_panel: "Панель администратора",
    adm_tab_stats: "Статистика",
    adm_tab_users: "Пользователи",
    adm_tab_sections: "Секции",
    adm_tab_bookings: "Бронирования",
    adm_tab_logs: "Логи",
    adm_total_users: "Всего пользователей",
    adm_students: "Студенты",
    adm_coaches: "Тренеры",
    adm_sections: "Секции",
    adm_bookings: "Бронирования",
    adm_messages: "Сообщений",
    adm_booking_statuses: "📊 Статусы бронирований",
    adm_pending: "Ожидают",
    adm_approved: "Принято",
    adm_cancelled: "Отменено",
    adm_schedule: "📅 Расписание",
    adm_schedule_entries: "Записей в расписании:",
    adm_search: "🔍 Поиск по имени или логину...",
    adm_people: "чел.",
    adm_col_id: "ID",
    adm_col_name: "ФИО",
    adm_col_login: "Логин",
    adm_col_role: "Роль",
    adm_col_group: "Группа",
    adm_col_student: "Студент",
    adm_col_section: "Секция",
    adm_col_date: "Дата",
    adm_col_status: "Статус",
    adm_role_admin: "Админ",
    adm_role_coach: "Тренер",
    adm_role_student: "Студент",
    adm_status_pending: "Ожидание",
    adm_status_approved: "Принят",
    adm_status_cancelled: "Отменён",
    adm_security_log: "ЖУРНАЛ БЕЗОПАСНОСТИ",
    adm_refresh: "↺ Обновить",
    adm_no_logs: "Нет записей",
    adm_delete_user: "Удалить пользователя?",
    adm_delete_section: "Удалить секцию?",
    adm_delete_booking: "Удалить запись?",
    se_title: "Моё расписание",
    se_add_lesson: "Добавить занятие",
    se_pick_day: "Выберите день недели",
    se_pick_section: "Выберите секцию",
    se_add_btn: "Добавить",
    se_save_btn: "Сохранить",
    se_empty: "Нет занятий",
    se_fill_all: "Заполните все поля",
    se_coach_only: "Доступ только для преподавателей",
    se_delete_confirm: "Удалить запись из расписания?",
    se_day_mon: "Понедельник",
    se_day_tue: "Вторник",
    se_day_wed: "Среда",
    se_day_thu: "Четверг",
    se_day_fri: "Пятница",
    att_title: "Посещаемость",
    att_all_students: "Все студенты",
    att_total: "Всего",
    att_present: "Присутствовал",
    att_absent: "Пропустил",
    att_attendance_pct: "Посещаемость:",
    att_no_records: "Записей о посещаемости нет",
    att_present_badge: "Присутствовал",
    att_absent_badge: "Пропустил",
    bc_title: "Подтвердить запись",
    bc_doc_upload: "Загрузка документов",
    bc_auto: "Автоматически",
    bc_manual: "Вручную",
    bc_coach: "Тренер:",
    bc_student: "Студент:",
    bc_date: "Дата подачи:",
    bc_confirm: "Подтвердить запись »",
    bc_no_coach: "Не назначен",
    bc_not_auth: "Необходимо войти в аккаунт",
    sl_title: "🏟️ Все секции",
    sl_no_place: "Место не указано",
    sl_no_coach: "Тренер не назначен",
    success_title: "Заявка подана",
    success_btn: "Другие секции",
    tb_no_requests: "Нет заявок",
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const t = (key) => T.ru[key] ?? key;

  return (
    <LangContext.Provider value={{ t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
